/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scientificcalculator;

/**
 *
 * @author viito
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    double num1,num2,result;
    String opr;
    
    public void enable()
    {
        txf_Box.setEnabled(true);
        
        btn_Root.setEnabled(true);
        btn_Root.setEnabled(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txf_Box = new javax.swing.JTextField();
        btn_Root = new javax.swing.JButton();
        btn_Sinh = new javax.swing.JButton();
        btn_Powert3 = new javax.swing.JButton();
        btn_Powert2 = new javax.swing.JButton();
        btn_Factorial = new javax.swing.JButton();
        btn_Expo = new javax.swing.JButton();
        btn_Cosh = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btn_Fraction = new javax.swing.JButton();
        btn_Sum = new javax.swing.JButton();
        btn_Sin = new javax.swing.JButton();
        btn_Tanh = new javax.swing.JButton();
        btn_Nine = new javax.swing.JButton();
        btn_Six = new javax.swing.JButton();
        btn_Three = new javax.swing.JButton();
        btn_Cos = new javax.swing.JButton();
        btn_Powery = new javax.swing.JButton();
        btn_Eight = new javax.swing.JButton();
        btn_Five = new javax.swing.JButton();
        btn_Two = new javax.swing.JButton();
        btn_Tan = new javax.swing.JButton();
        btn_Percentage = new javax.swing.JButton();
        btn_Seven = new javax.swing.JButton();
        btn_Four = new javax.swing.JButton();
        btn_One = new javax.swing.JButton();
        btn_Complement = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        btn_Minus = new javax.swing.JButton();
        btn_Zero = new javax.swing.JButton();
        btn_Equals = new javax.swing.JButton();
        btn_Log = new javax.swing.JButton();
        btn_Backspace = new javax.swing.JButton();
        btn_Times = new javax.swing.JButton();
        btn_Divide = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scientific Calculator");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        txf_Box.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txf_Box.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btn_Root.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Root.setText("R");
        btn_Root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RootActionPerformed(evt);
            }
        });

        btn_Sinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Sinh.setText("sinh");
        btn_Sinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SinhActionPerformed(evt);
            }
        });

        btn_Powert3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Powert3.setText("x^3");
        btn_Powert3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Powert3ActionPerformed(evt);
            }
        });

        btn_Powert2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Powert2.setText("x^2");
        btn_Powert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Powert2ActionPerformed(evt);
            }
        });

        btn_Factorial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Factorial.setText("n!");
        btn_Factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FactorialActionPerformed(evt);
            }
        });

        btn_Expo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Expo.setText("exp");
        btn_Expo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExpoActionPerformed(evt);
            }
        });

        btn_Cosh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Cosh.setText("cosh");
        btn_Cosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CoshActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("+/-");

        btn_Fraction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Fraction.setText(".");
        btn_Fraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FractionActionPerformed(evt);
            }
        });

        btn_Sum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Sum.setText("+");
        btn_Sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SumActionPerformed(evt);
            }
        });

        btn_Sin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Sin.setText("sin");
        btn_Sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SinActionPerformed(evt);
            }
        });

        btn_Tanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Tanh.setText("tanh");
        btn_Tanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TanhActionPerformed(evt);
            }
        });

        btn_Nine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Nine.setText("9");
        btn_Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NineActionPerformed(evt);
            }
        });

        btn_Six.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Six.setText("6");
        btn_Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SixActionPerformed(evt);
            }
        });

        btn_Three.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Three.setText("3");
        btn_Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThreeActionPerformed(evt);
            }
        });

        btn_Cos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Cos.setText("cos");
        btn_Cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CosActionPerformed(evt);
            }
        });

        btn_Powery.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Powery.setText("x^y");
        btn_Powery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PoweryActionPerformed(evt);
            }
        });

        btn_Eight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Eight.setText("8");
        btn_Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EightActionPerformed(evt);
            }
        });

        btn_Five.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Five.setText("5");
        btn_Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FiveActionPerformed(evt);
            }
        });

        btn_Two.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Two.setText("2");
        btn_Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TwoActionPerformed(evt);
            }
        });

        btn_Tan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Tan.setText("tan");
        btn_Tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TanActionPerformed(evt);
            }
        });

        btn_Percentage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Percentage.setText("%");
        btn_Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PercentageActionPerformed(evt);
            }
        });

        btn_Seven.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Seven.setText("7");
        btn_Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SevenActionPerformed(evt);
            }
        });

        btn_Four.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Four.setText("4");
        btn_Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FourActionPerformed(evt);
            }
        });

        btn_One.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_One.setText("1");
        btn_One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OneActionPerformed(evt);
            }
        });

        btn_Complement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Complement.setText("1/x");
        btn_Complement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ComplementActionPerformed(evt);
            }
        });

        btn_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Clear.setText("Clr");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_Minus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Minus.setText("-");
        btn_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MinusActionPerformed(evt);
            }
        });

        btn_Zero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Zero.setText("0");
        btn_Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ZeroActionPerformed(evt);
            }
        });

        btn_Equals.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Equals.setText("=");
        btn_Equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EqualsActionPerformed(evt);
            }
        });

        btn_Log.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Log.setText("log");
        btn_Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogActionPerformed(evt);
            }
        });

        btn_Backspace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Backspace.setText("<-");
        btn_Backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackspaceActionPerformed(evt);
            }
        });

        btn_Times.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Times.setText("*");
        btn_Times.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimesActionPerformed(evt);
            }
        });

        btn_Divide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Divide.setText("/");
        btn_Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DivideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txf_Box)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Root, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Sinh, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Powert3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Powert2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Expo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Cosh, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Fraction, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Sin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Tanh, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Six, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Three, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Cos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Powery, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Eight, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Five, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Two, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Tan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Seven, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Four, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_One, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Complement, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(btn_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(btn_Minus, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(btn_Zero, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Log, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Times, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_Equals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txf_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_Root, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Sinh, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Powert3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Powert2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_Expo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Cosh, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Fraction, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_Sin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_Cos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Tanh, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Six, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Three, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_Tan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Seven, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Four, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_One, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_Complement, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btn_Log, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_Backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_Times, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)))
                            .addComponent(btn_Equals, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(btn_Powery, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Eight, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Five, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Two, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExpoActionPerformed
        double t=Math.exp(Double.parseDouble(txf_Box.getText()));
       
       txf_Box.setText("");
       txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_ExpoActionPerformed

    private void btn_ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ZeroActionPerformed
        txf_Box.setText(txf_Box.getText() + "0");
    }//GEN-LAST:event_btn_ZeroActionPerformed

    private void btn_OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OneActionPerformed
        txf_Box.setText(txf_Box.getText() + "1");
    }//GEN-LAST:event_btn_OneActionPerformed

    private void btn_TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TwoActionPerformed
        txf_Box.setText(txf_Box.getText() + "2");
    }//GEN-LAST:event_btn_TwoActionPerformed

    private void btn_ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThreeActionPerformed
        txf_Box.setText(txf_Box.getText() + "3");
    }//GEN-LAST:event_btn_ThreeActionPerformed

    private void btn_FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FourActionPerformed
        txf_Box.setText(txf_Box.getText() + "4");
    }//GEN-LAST:event_btn_FourActionPerformed

    private void btn_FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FiveActionPerformed
       txf_Box.setText(txf_Box.getText() + "5");
    }//GEN-LAST:event_btn_FiveActionPerformed

    private void btn_SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SixActionPerformed
        txf_Box.setText(txf_Box.getText() + "6");
    }//GEN-LAST:event_btn_SixActionPerformed

    private void btn_SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SevenActionPerformed
        txf_Box.setText(txf_Box.getText() + "7");
    }//GEN-LAST:event_btn_SevenActionPerformed

    private void btn_EightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EightActionPerformed
        txf_Box.setText(txf_Box.getText() + "8");
    }//GEN-LAST:event_btn_EightActionPerformed

    private void btn_NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NineActionPerformed
        txf_Box.setText(txf_Box.getText() + "9");
    }//GEN-LAST:event_btn_NineActionPerformed

    private void btn_FractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FractionActionPerformed
       txf_Box.setText(txf_Box.getText() + ".");
    }//GEN-LAST:event_btn_FractionActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        txf_Box.setText("");
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_BackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackspaceActionPerformed
        String backSpace = null;
        
        if (txf_Box.getText().length() > 0)
        {
            StringBuilder S = new StringBuilder (txf_Box.getText());
            
            S.deleteCharAt(txf_Box.getText().length() - 1);
            backSpace = S.toString();
            txf_Box.setText(backSpace);
        }
    }//GEN-LAST:event_btn_BackspaceActionPerformed

    private void btn_SumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SumActionPerformed
       num1 = Double.parseDouble(txf_Box.getText());
       
       txf_Box.setText("");
       
       opr = "+";
    }//GEN-LAST:event_btn_SumActionPerformed

    private void btn_MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MinusActionPerformed
        num1 = Double.parseDouble(txf_Box.getText());
       
       txf_Box.setText("");
       
       opr = "-";
    }//GEN-LAST:event_btn_MinusActionPerformed

    private void btn_TimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimesActionPerformed
         num1 = Double.parseDouble(txf_Box.getText());
       
       txf_Box.setText("");
       
       opr = "*";
    }//GEN-LAST:event_btn_TimesActionPerformed

    private void btn_DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DivideActionPerformed
         num1 = Double.parseDouble(txf_Box.getText());
       
       txf_Box.setText("");
       
       opr = "/";
    }//GEN-LAST:event_btn_DivideActionPerformed

    private void btn_PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PercentageActionPerformed
        num1 = Double.parseDouble(txf_Box.getText());
       
       txf_Box.setText("");
       
       opr = "%";
    }//GEN-LAST:event_btn_PercentageActionPerformed

    private void btn_EqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EqualsActionPerformed
        num2 = Double.parseDouble(txf_Box.getText());
        
        if(opr == "+")
        {
            result = num1 + num2;
            txf_Box.setText(Double.toString(result));
        }
        
        else if(opr == "-")
        {
            result = num1 - num2;
            txf_Box.setText(Double.toString(result));
            
        }
        
        else if(opr == "*")
        {
            result = num1 * num2;
            txf_Box.setText(Double.toString(result));
        }
        
        else if (opr == "/")
        {
            result = num1 / num2;
            txf_Box.setText(Double.toString(result));
        }
        
        else if (opr == "%")
        {
            result = num1%num2;
            txf_Box.setText(Double.toString(result));
            
        }
        
        else if (opr == "x^y")
        {
            
            
            for(int i=0; i<num2; i++) {
                result = num1*num2;
            }
            txf_Box.setText(Double.toString(result));
        
        }
    }//GEN-LAST:event_btn_EqualsActionPerformed

    private void btn_SinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SinActionPerformed
       double t=Math.sin(Double.parseDouble(txf_Box.getText()));
       
       txf_Box.setText("");
       txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_SinActionPerformed

    private void btn_CosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CosActionPerformed
         double t=Math.cos(Double.parseDouble(txf_Box.getText()));
       
       txf_Box.setText("");
       txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_CosActionPerformed

    private void btn_TanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TanActionPerformed
         double t=Math.tan(Double.parseDouble(txf_Box.getText()));
       
       txf_Box.setText("");
       txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_TanActionPerformed

    private void btn_SinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SinhActionPerformed
         double t=Math.sinh(Double.parseDouble(txf_Box.getText()));
       
       txf_Box.setText("");
       txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_SinhActionPerformed

    private void btn_CoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CoshActionPerformed
         double t=Math.cosh(Double.parseDouble(txf_Box.getText()));
       
       txf_Box.setText("");
       txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_CoshActionPerformed

    private void btn_TanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TanhActionPerformed
         double t=Math.tanh(Double.parseDouble(txf_Box.getText()));
       
       txf_Box.setText("");
       txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_TanhActionPerformed

    private void btn_LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogActionPerformed
         double t=Math.log(Double.parseDouble(txf_Box.getText()));
       
       txf_Box.setText("");
       txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_LogActionPerformed

    private void btn_RootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RootActionPerformed
        double t=Math.sqrt(Double.parseDouble(txf_Box.getText()));
       
       txf_Box.setText("");
       txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_RootActionPerformed

    private void btn_ComplementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ComplementActionPerformed
         double t=1/(Double.parseDouble(txf_Box.getText()));
       
       txf_Box.setText("");
       txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_ComplementActionPerformed

    private void btn_Powert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Powert2ActionPerformed
        double t= Double.parseDouble(txf_Box.getText());
        
        t=t*t;
        txf_Box.setText("");
        txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_Powert2ActionPerformed

    private void btn_Powert3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Powert3ActionPerformed
         double t= Double.parseDouble(txf_Box.getText());
        
        t=t*t*t;
        txf_Box.setText("");
        txf_Box.setText(txf_Box.getText() + t);
    }//GEN-LAST:event_btn_Powert3ActionPerformed

    private void btn_PoweryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PoweryActionPerformed
        num1 = Double.parseDouble(txf_Box.getText());
        
        txf_Box.setText("");
        
        opr = "x^y";
    }//GEN-LAST:event_btn_PoweryActionPerformed

    private void btn_FactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FactorialActionPerformed
        double t=Double.parseDouble(txf_Box.getText());
        
        double fact=1;
        while(t!=0)
        {
            fact = fact*t;
            t--;
        
        }
        txf_Box.setText("");
        txf_Box.setText(txf_Box.getText() + fact);
    }//GEN-LAST:event_btn_FactorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Backspace;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Complement;
    private javax.swing.JButton btn_Cos;
    private javax.swing.JButton btn_Cosh;
    private javax.swing.JButton btn_Divide;
    private javax.swing.JButton btn_Eight;
    private javax.swing.JButton btn_Equals;
    private javax.swing.JButton btn_Expo;
    private javax.swing.JButton btn_Factorial;
    private javax.swing.JButton btn_Five;
    private javax.swing.JButton btn_Four;
    private javax.swing.JButton btn_Fraction;
    private javax.swing.JButton btn_Log;
    private javax.swing.JButton btn_Minus;
    private javax.swing.JButton btn_Nine;
    private javax.swing.JButton btn_One;
    private javax.swing.JButton btn_Percentage;
    private javax.swing.JButton btn_Powert2;
    private javax.swing.JButton btn_Powert3;
    private javax.swing.JButton btn_Powery;
    private javax.swing.JButton btn_Root;
    private javax.swing.JButton btn_Seven;
    private javax.swing.JButton btn_Sin;
    private javax.swing.JButton btn_Sinh;
    private javax.swing.JButton btn_Six;
    private javax.swing.JButton btn_Sum;
    private javax.swing.JButton btn_Tan;
    private javax.swing.JButton btn_Tanh;
    private javax.swing.JButton btn_Three;
    private javax.swing.JButton btn_Times;
    private javax.swing.JButton btn_Two;
    private javax.swing.JButton btn_Zero;
    private javax.swing.JButton jButton10;
    private javax.swing.JTextField txf_Box;
    // End of variables declaration//GEN-END:variables
}
